image: python:3.8

pipelines:
  pull-requests:
    "**":
      - step:
          name: Lint code
          caches:
            - pip
          script:
            - sudo apt install luarocks
            - sudo apt install lua5.1
            - luarocks install luacheck
            - luacheck .
