image: atlassian/default-image:3

pipelines:
    pull-requests:
        "**":
            - step:
                name: Lint code
                script:
                    - apt-get update
                    - apt-get -y install lua5.1
                    - apt-get -y install luarocks
                    - luarocks install luacheck
                    - luacheck .
    branches:
        master:
            - step:
                name: Lint code
                script:
                    - apt-get update
                    - apt-get -y install lua5.1
                    - apt-get -y install luarocks
                    - luarocks install luacheck
                    - luacheck .
    tags:
        "*":
            - step:
                name: Deploy to ContentDB
                script:
                    - apt-get update
                    - apt-get -y install lua5.1
                    - apt-get -y install luarocks
                    - luarocks install luacheck
                    - luacheck .
                    - curl --location --request POST 'https://content.minetest.net/api/packages/SaKeL/x_bows/releases/new/' --header 'Authorization:Bearer $CONTENT_DB_X_BOWS_TOKEN' --header 'Content-Type:application/json' --data-raw '{"method":"git", "title":"$BITBUCKET_TAG", "ref":"master"}'
