image: atlassian/default-image:3

pipelines:
  pull-requests:
    "**":
      - step:
          name: Lint code
          script:
            - sudo apt install luarocks
            - sudo apt install lua5.1
            - luarocks install luacheck
            - luacheck .
