name = x_bows
title = X Bows
author = SaKeL
description = Adds bows, arrows, and quivers with rich animations, ballistic flight physics, particle effects, and an extensible API.
depends =
optional_depends = default, farming, 3d_armor, mesecons, playerphysics, player_monoids, wool, i3, unified_inventory, simple_skins, u_skins, wardrobe, sfinv, skinsdb, player_api, x_player_api, pova, bones, x_enchanting, deathstats
supported_games = minetest_game
min_minetest_version = 5.6.1
